export const repos = [
  {
    name: "Grotteko",
    description: "Portfolio website for professional music producer and mixing engineer Andreas Johanson, featuring a custom built audio player for showcasing the great tunes.",
    repoUrl: null,
    demoUrl: "https://grotteko.com/",
    tags: ["html", "typescript", "scss", "vite"],
  },
  {
    name: "Folk från Skogen",
    description: "Official website for a summer music festival taking place in Gullabo Sweden",
    repoUrl: "https://github.com/simon-off/folk-fran-skogen",
    demoUrl: "https://folkfranskogen.se/",
    tags: ["html", "javascript", "scss", "vite"],
  },
  {
    name: "Electricity Calculator",
    description: "Blazor webassembly app designed to calculate your total energy use and cost, over a chosen period of time",
    repoUrl: "https://github.com/simon-off/electricity-calculator",
    demoUrl: "https://electricitycalculator.netlify.app/",
    tags: ["blazor", "csharp", "picocss", "webassembly"],
  },
  {
    name: "Inet Redesign",
    description: "Clone & redesign of the home page over at inet.se made with React, TypeScript & Tailwind CSS",
    repoUrl: "https://github.com/simon-off/inet-redesign",
    demoUrl: "https://inet-redesign.netlify.app/",
    tags: ["ecommerce", "react", "tailwindcss", "typescript"],
  },
  {
    name: "React Interview Questions",
    description: "A simple react web app that contains multiple react interview coding challenges",
    repoUrl: "https://github.com/simon-off/react-interview-questions",
    demoUrl: "https://react-interview-questions.netlify.app",
    tags: ["frontend", "react", "scss", "typescript"],
  },
  {
    name: "Another Movie Database",
    description: "Movie database app made with React.js & lots of sass, using data from themoviedb.org public api",
    repoUrl: "https://github.com/simon-off/another-movie-database",
    demoUrl: "https://anothermoviedatabase.netlify.app/",
    tags: ["react", "scss"],
  },
  {
    name: "BPM Tap",
    description: "Tap tempo tool for finding the BPM of a song",
    repoUrl: "https://github.com/simon-off/bpm-tap",
    demoUrl: "https://bpm-tap.netlify.app/",
    tags: ["html", "css", "javascript"],
  },
  {
    name: "We Hate Music",
    description: "Personal music project site, including a side scrolling spaceship shooter game made in the godot game engine",
    repoUrl: null,
    demoUrl: "/wehatemusic",
    tags: ["html", "css", "javascript", "godot"],
  },
  {
    name: "Snek",
    description: "Classic snake game made with way too many divs...",
    repoUrl: "https://github.com/simon-off/snek",
    demoUrl: "https://snek2000.netlify.app/",
    tags: ["html", "css", "javascript"],
  },
];
