// import "@fontsource/poppins";
import "@fontsource/poppins/900-italic.css";
import "@fontsource/rubik";
import "@fontsource/rubik/300.css";
import "@fontsource/jetbrains-mono";
import "@fontsource/jetbrains-mono/500.css";
import "./scss/main.scss";
import "./js/zigzag";
import "./js/onload";
import "./js/repos";
